### ISSUE TITLE
please include LICENSE.txt in the sources uploaded to crates.io

### ISSUE THREAD

**Issue by decathorpe** [myrrlyn/wyz#2]
There exist more than 20 variants of *the* "MIT" license.

Side note: Unless I did my comparison wrong, you seem to have chosen the "Modern Style with sublicense", as it is classified by the Fedora project: https://fedoraproject.org/wiki/Licensing:MIT?rd=Licensing/MIT#Modern_Style_with_sublicense

Your LICENSE.txt text states:

> The above copyright notice and this permission notice shall be included
> in all copies or substantial portions of the Software.

So, to clarify which "MIT" license actually applies, and to adhere to the text of the chosen license, please include the LICENSE.txt file with the crate published to crates.io. Adding a "LICENSE.txt" entry to the "include" array in Cargo.toml should do that.

**Comment by decathorpe** [comment]
The same "`readme = "README.md"` in Cargo.toml but the file is not included in published crates" [comment](https://github.com/myrrlyn/tap/issues/2#issuecomment-732964803) applies here as well.

**Comment by myrrlyn** [comment]
Hey thanks for checking these things, by the way. I (obviously) completely overlook them so I appreciate your reports. This will be fixed in the next publish.

**Comment by decathorpe** [comment]
No problem. I need to routinely check these things when including Rust crates in fedora, so it's no additional trouble. :) Thanks for the fixes!
