### ISSUE TITLE
typemap dependency with vulnerable traitobject

### ISSUE THREAD

**Issue by kornelski** [myrrlyn/wyz#8]
Typemap depends on unsafe-any, which depends on traitobject, which has [a security vulnerability](https://rustsec.org/advisories/RUSTSEC-2020-0027).

This crate is a dependency of bitvec, which in turn makes a ton of crates have the vulnerable traitobject in their Cargo.lock, which makes security-scanning tools upset.

Can you drop typemap?

**Comment by myrrlyn** [comment]
`typemap` is only used by the `garbage` feature, which is not default nor used by `bitvec`. It *shouldn't* be appearing in dependency trees through `bitvec`, and in point of fact does not when I run `cargo tree`:

```text
$ cargo tree
bitvec v1.0.1 (/Users/myrrlyn/Projects/bitvecto-rs/bitvec)
├── funty v2.0.0
├── radium v0.7.0
├── tap v1.0.1
└── wyz v0.5.0
    └── tap v1.0.1
[dev-dependencies]
```

Regardless, the `wm` module was a one-shot idea I wanted to sketch out and I am never going to actually use it. I have stripped it in 0.6, and will be updating `bitvec` to use it in the near future.
