### ISSUE TITLE
0.5.0 is published on crates.io yet unavailable here

### ISSUE THREAD

**Issue by kayabaNerve** [myrrlyn/wyz#9]
Would you please correct this? This has been cited elsewhere for ~1 month, yet it doesn't appear to have been reported here due to this library being seemingly unmaintained (having insecure dependencies in tree and lack of replies to #8). While I don't mean to ask you to commit your entire life to working on wyz and handling every random issue, having the source code be published properly would be appreciated.

**Comment by myrrlyn** [comment]
Yeah sorry. It's been a long ... couple years. Should be synced now.

**Comment by kayabaNerve** [comment]
Thank you! It's greatly appreciated.

**Comment by dpc** [comment]
Thanks a lot! Appreciated!
